#define TRIG_PIN 12
#define ECHO_PIN 11
#define LASER_PIN 33
#define SERVOMIN 150
#define SERVOMAX 600

#define COLLISION_DISTANCE 15
#define ANGLE_CENTER 370
#define ANGLE_LEFT 100
#define ANGLE_RIGHT 600
#define ANGLE_JOINT_1_UP 150
#define ANGLE_JOINT_2_UP 500
#define ANGLE_JOINT_1_DOWN 380
#define ANGLE_JOINT_2_DOWN 650
#define GRIPPER_OPEN 100
#define GRIPPER_CLOSED 250
#define GRIPPER_HORIZONTAL 100
#define GRIPPER_VERTICAL 340

#define CATERPILLAR_LEFT 52
#define CATERPILLAR_RIGHT 42
#define CATERPILLAR_LEFT_FORWARD 48
#define CATERPILLAR_LEFT_BACKWARD 50
#define CATERPILLAR_RIGHT_FORWARD 44
#define CATERPILLAR_RIGHT_BACKWARD 46

#define ARM_BASE 0
#define ARM_JOINT_1 1
#define ARM_JOINT_2 2
#define ARM_JOINT_3 3
#define ARM_JOINT_4 4
#define ARM_EOAT 5

#define ROBOT_LASER_TOGGLE "0"

#define ROBOT_END_EFFECTOR_OPEN "1"
#define ROBOT_END_EFFECTOR_CLOSE "2"
#define ROBOT_END_EFFECTOR_ROTATE "3"

#define ROBOT_ARM_MOVE_UP "4"
#define ROBOT_ARM_MOVE_DOWN "5"
#define ROBOT_ARM_MOVE_LEFT "6"
#define ROBOT_ARM_MOVE_RIGHT "7"
#define ROBOT_ARM_CENTERED "8"

#define ROBOT_ARM_REST_TOGGLE "9"
#define ROBOT_ARM_DEMO "10"
#define ROBOT_ARM_POWER_TOGGLE "11"

#define ROBOT_ARM_CUSTOM_HORIZONTAL_MOVEMENT "rth"
#define ROBOT_ARM_CUSTOM_VERTICAL_MOVEMENT "rtv"

#define ROBOT_CATERPILLAR_STOP "20"
#define ROBOT_CATERPILLAR_MOVE_FORWARD "21"
#define ROBOT_CATERPILLAR_MOVE_BACKWARD "22"
#define ROBOT_CATERPILLAR_MOVE_LEFT "23"
#define ROBOT_CATERPILLAR_MOVE_RIGHT "24"

#define REMOTE_REWIND 68
#define REMOTE_FAST_FORWARD 67
#define REMOTE_EQ 25
#define REMOTE_VOL_UP 70
#define REMOTE_VOL_DOWN 21
#define REMOTE_NUMPAD_0 22
#define REMOTE_ST_REPT 13
#define REMOTE_ARROW_DOWN 7
#define REMOTE_ARROW_UP 9
#define REMOTE_PAUSE 64
#define REMOTE_FUNC_STOP 71
#define REMOTE_POWER 69
#define REMOTE_NUMPAD_5 28
#define REMOTE_NUMPAD_2 24
#define REMOTE_NUMPAD_8 82
#define REMOTE_NUMPAD_4 8
#define REMOTE_NUMPAD_6 90